name: ImmortalWrt Packages Build Bot
on:
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/build-packages-release.yml'
      - 'patch.sh'
      - 'do_not_build'
      - 'packages/**'
      - '!packages/**/github/workflows/**'
      - '!packages/**/README*'
      - '!packages/**/.gitignore'
      - '!packages/**/LICENSE'
      - '!packages/**/LICENSES'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }} / ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64_generic
        version:
          - "25.12"
    env:
      SDK_ARCH: ${{ format('{0}-openwrt-{1}', matrix.arch, matrix.version) }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          ./patch.sh "$SDK_ARCH"
          ls packages | sort > package-list.txt
          sort do_not_build -o do_not_build
          comm -23 package-list.txt do_not_build > packages-to-build.txt
          echo "PACKAGES=$(paste -sd' ' packages-to-build.txt)" >> "$GITHUB_ENV"
          find . -name "Makefile" -type f -exec cat {} \;

      - name: Build
        uses: immortalwrt/gh-action-sdk@master
        env:
          ARCH: ${{ env.SDK_ARCH }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          INDEX: "1"
          IGNORE_ERRORS: "1"
          BUILD_LOG: "1"
          NO_SHFMT_CHECK: "1"
          NO_REFRESH_CHECK: "1"
          PACKAGES: ${{ env.PACKAGES }}
          FEEDNAME: "mywrt"
          V: "s"

      - name: List files
        run: |
          ls -R bin/

      - name: Stage versioned packages
        run: |
          mkdir artifact-packages
          mv bin/packages "artifact-packages/packages-${{ matrix.version }}"

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: packages-${{ env.SDK_ARCH }}
          path: artifact-packages
          if-no-files-found: error
          retention-days: 1

  upload:
    name: Upload
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download packages
        uses: actions/download-artifact@v8
        with:
          pattern: packages-*
          path: dist
          merge-multiple: true

      - name: Set up rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Upload Packages to remote bucket
        run: rclone copy "dist" "remote:ImmortalWRT"
